#!/bin/bash

# Commands to run on VPS to update backend
echo "🔧 Commands to run on VPS (3.26.45.220):"
echo ""
echo "1️⃣ SSH into VPS:"
echo "   ssh ubuntu@3.26.45.220"
echo ""
echo "2️⃣ Navigate to backend directory:"
echo "   cd /home/ubuntu/aztec_meme_vote/backend"
echo ""
echo "3️⃣ Update server.js with fixes:"
echo "   nano server.js"
echo ""
echo "4️⃣ Or copy the updated server.js content:"
echo "   cat > server.js << 'EOF'"
echo ""
echo "5️⃣ Restart the backend:"
echo "   pm2 restart aztec-backend"
echo ""
echo "6️⃣ Check status:"
echo "   pm2 status"
echo ""
echo "7️⃣ Test the API:"
echo "   curl -s https://3.26.45.220/api/health"
echo ""
echo "📋 Manual steps to update backend:"
echo "   1. SSH ke VPS: ssh ubuntu@3.26.45.220"
echo "   2. Masuk ke direktori: cd /home/ubuntu/aztec_meme_vote/backend"
echo "   3. Edit server.js: nano server.js"
echo "   4. Copy paste kode server.js yang sudah diperbaiki"
echo "   5. Restart: pm2 restart aztec-backend"
echo "   6. Test: curl https://3.26.45.220/api/health" 